/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package novosistcalmargemdefaturamento;

/**
 *
 * @author Windows Pro
 */
public class TelaReceitaDespesas extends javax.swing.JFrame {

    /**
     * Creates new form TelaReceitaDespesas
     */
    public TelaReceitaDespesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tituloFaturamento = new javax.swing.JLabel();
        tituloFaturamento2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tituloDespesas = new javax.swing.JLabel();
        tituloMaterialExpediente = new javax.swing.JLabel();
        tituloImpostos1 = new javax.swing.JLabel();
        tituloEnergia = new javax.swing.JLabel();
        tituloPlanoDeInternet = new javax.swing.JLabel();
        tituloCombustivel = new javax.swing.JLabel();
        tituloPlanTelefonico1 = new javax.swing.JLabel();
        tituloAlimentacao = new javax.swing.JLabel();
        tituloOutros = new javax.swing.JLabel();
        resultadoFaturamento = new javax.swing.JTextField();
        resultadoImpostos = new javax.swing.JTextField();
        resultadoMaterialExpediente = new javax.swing.JTextField();
        resultadoEnergia = new javax.swing.JTextField();
        resultadoPlanoInternet = new javax.swing.JTextField();
        resultadoPlanoTelefonico = new javax.swing.JTextField();
        resultadoCombustivel = new javax.swing.JTextField();
        resultadoAlimentacao = new javax.swing.JTextField();
        resultadoOutros = new javax.swing.JTextField();
        botaoCalcularLucro = new javax.swing.JButton();
        tituloApuracaoFinal = new javax.swing.JLabel();
        resultadoApuracaoFinal = new javax.swing.JTextField();
        botaoFinalizar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LANÇAMENTOS");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setForeground(new java.awt.Color(51, 0, 51));

        tituloFaturamento.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        tituloFaturamento.setText("Receita do Mês");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(tituloFaturamento)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloFaturamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tituloFaturamento2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloFaturamento2.setForeground(new java.awt.Color(255, 255, 255));
        tituloFaturamento2.setText("Faturamento");

        tituloDespesas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        tituloDespesas.setText("Despesas do Mês");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(tituloDespesas)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tituloMaterialExpediente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloMaterialExpediente.setForeground(new java.awt.Color(255, 255, 255));
        tituloMaterialExpediente.setText("Material de Expediente");

        tituloImpostos1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloImpostos1.setForeground(new java.awt.Color(255, 255, 255));
        tituloImpostos1.setText("Impostos");

        tituloEnergia.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloEnergia.setForeground(new java.awt.Color(255, 255, 255));
        tituloEnergia.setText("Energia");

        tituloPlanoDeInternet.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloPlanoDeInternet.setForeground(new java.awt.Color(255, 255, 255));
        tituloPlanoDeInternet.setText("Plano de Internet");

        tituloCombustivel.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloCombustivel.setForeground(new java.awt.Color(255, 255, 255));
        tituloCombustivel.setText("Combustível");

        tituloPlanTelefonico1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloPlanTelefonico1.setForeground(new java.awt.Color(255, 255, 255));
        tituloPlanTelefonico1.setText("Plano Telefônico");

        tituloAlimentacao.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloAlimentacao.setForeground(new java.awt.Color(255, 255, 255));
        tituloAlimentacao.setText("Alimentação");

        tituloOutros.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloOutros.setForeground(new java.awt.Color(255, 255, 255));
        tituloOutros.setText("Outros");

        resultadoCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoCombustivelActionPerformed(evt);
            }
        });

        botaoCalcularLucro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        botaoCalcularLucro.setForeground(new java.awt.Color(204, 0, 0));
        botaoCalcularLucro.setText("Calcular Lucro");
        botaoCalcularLucro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCalcularLucroMouseClicked(evt);
            }
        });

        tituloApuracaoFinal.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tituloApuracaoFinal.setForeground(new java.awt.Color(204, 255, 255));
        tituloApuracaoFinal.setText("O Lucro Líquido do Mês e Margem de Lucro (%) foram, respectivamente:");

        resultadoApuracaoFinal.setBackground(new java.awt.Color(204, 255, 255));
        resultadoApuracaoFinal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        resultadoApuracaoFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultadoApuracaoFinalMouseClicked(evt);
            }
        });
        resultadoApuracaoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoApuracaoFinalActionPerformed(evt);
            }
        });

        botaoFinalizar.setText("Finalizar");
        botaoFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoFinalizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloPlanoDeInternet)
                        .addGap(69, 69, 69)
                        .addComponent(resultadoPlanoInternet)
                        .addGap(18, 18, 18)
                        .addComponent(tituloCombustivel)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoFaturamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloImpostos1)
                                            .addComponent(tituloMaterialExpediente))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resultadoImpostos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(resultadoMaterialExpediente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tituloEnergia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resultadoEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloPlanTelefonico1)
                                    .addComponent(tituloOutros)
                                    .addComponent(tituloAlimentacao)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(tituloFaturamento2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(resultadoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultadoAlimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultadoOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultadoPlanoTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tituloApuracaoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(resultadoApuracaoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoFinalizar)
                            .addGap(26, 26, 26)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(botaoCalcularLucro)
                        .addGap(194, 194, 194))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloFaturamento2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloImpostos1)
                    .addComponent(resultadoImpostos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloAlimentacao)
                    .addComponent(resultadoAlimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloMaterialExpediente)
                            .addComponent(resultadoMaterialExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloOutros))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resultadoEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tituloPlanTelefonico1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(resultadoPlanoInternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tituloCombustivel)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tituloEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tituloPlanoDeInternet))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(resultadoOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(resultadoPlanoTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(botaoCalcularLucro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloApuracaoFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoApuracaoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFinalizar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(527, 391));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCalcularLucroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCalcularLucroMouseClicked

        double total = Double.parseDouble(resultadoFaturamento.getText());
        double imposto = Double.parseDouble(resultadoImpostos.getText());
        double energia = Double.parseDouble(resultadoEnergia.getText());
        double materialExpediente = Double.parseDouble(resultadoMaterialExpediente.getText());
        double planoInternet = Double.parseDouble(resultadoPlanoInternet.getText());
        double planoTelefonico = Double.parseDouble(resultadoPlanoTelefonico.getText());
        double combustivel = Double.parseDouble(resultadoCombustivel.getText());
        double alimentacao = Double.parseDouble(resultadoAlimentacao.getText());
        double outros = Double.parseDouble(resultadoOutros.getText());
        double resultado = imposto + energia + materialExpediente + planoInternet + planoTelefonico + combustivel + alimentacao + outros;
        double r = total - resultado;
        double res = r / total * 100;
        System.out.println(r);
        System.out.println(res);

//System.out.println("total " - "imposto" - "energia" - "materialExpediente" - "planoInternet" - "planoTelefonico" - "combustivel" - "alimentacao" - "outros");
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCalcularLucroMouseClicked

    private void resultadoCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoCombustivelActionPerformed

    private void resultadoApuracaoFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultadoApuracaoFinalMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoApuracaoFinalMouseClicked

    private void resultadoApuracaoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoApuracaoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoApuracaoFinalActionPerformed

    private void botaoFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFinalizarMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoFinalizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReceitaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReceitaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReceitaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReceitaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReceitaDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcularLucro;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField resultadoAlimentacao;
    private javax.swing.JTextField resultadoApuracaoFinal;
    private javax.swing.JTextField resultadoCombustivel;
    private javax.swing.JTextField resultadoEnergia;
    private javax.swing.JTextField resultadoFaturamento;
    private javax.swing.JTextField resultadoImpostos;
    private javax.swing.JTextField resultadoMaterialExpediente;
    private javax.swing.JTextField resultadoOutros;
    private javax.swing.JTextField resultadoPlanoInternet;
    private javax.swing.JTextField resultadoPlanoTelefonico;
    private javax.swing.JLabel tituloAlimentacao;
    private javax.swing.JLabel tituloApuracaoFinal;
    private javax.swing.JLabel tituloCombustivel;
    private javax.swing.JLabel tituloDespesas;
    private javax.swing.JLabel tituloEnergia;
    private javax.swing.JLabel tituloFaturamento;
    private javax.swing.JLabel tituloFaturamento2;
    private javax.swing.JLabel tituloImpostos1;
    private javax.swing.JLabel tituloMaterialExpediente;
    private javax.swing.JLabel tituloOutros;
    private javax.swing.JLabel tituloPlanTelefonico1;
    private javax.swing.JLabel tituloPlanoDeInternet;
    // End of variables declaration//GEN-END:variables
}
